### ISSUE TITLE
Simplify config files

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#1]
Right now there is too much files in the `config` folder, both YAML and JSON. We need to get down to one single config file that contains all the options

**Comment by christopheradams** [comment]
`dev.json` can be deleted, since Node prefers `development`

The empty `.json` files could be empty `.yaml` files instead, but I believe they must be there since you need at least one config file per environment.

Some  environments require `.js` files because they run code during configuration, but I don't think it would be convenient to use JS for all config.
