### ISSUE TITLE
Less expensive proof-of-existence?

### ISSUE THREAD

**Issue by ppKrauss** [proofofexistence/proofofexistence#40]
About the price. Today *5 mBTC = ~37.7 US$*  is expensive for a "notary public service"... It is possible to reduce this value?
To the current "notary market"  *0.5 mBTC* or less.

**Comment by rejon** [comment]
My current idea is to have a weekly price update to maintain stability. @christopheradams what do you think?

**Comment by rejon** [comment]
Yes, highest priority final issue IMO. And most automatable, should be in announcement.

**Comment by christopheradams** [comment]
The document certification price has been configured at 0.5 mBTC since the site has relaunched. However, some references in other media (e.g., Wikipedia) may quote an older 5 mBTC price.

To help things further, we're rolling out a dynamic pricing feature to keep the price closer to the mining fee, but without seeming arbitrary or changing too often. Currently that is 0.25 mBTC.

The current price will be listed on the home page and each document registration page.

**Comment by rejon** [comment]
This is great work.

Jon
